# This rule is not used by the project helloworld-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the learning.aca.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: helloworld-controller
    app.kubernetes.io/managed-by: kustomize
  name: helloworld-editor-role
rules:
- apiGroups:
  - learning.aca.com
  resources:
  - helloworlds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - learning.aca.com
  resources:
  - helloworlds/status
  verbs:
  - get
